"""ai-orch CLI — Typer entry point (registered in pyproject as `ai-orch`).

WHY this file stays thin: each @app.command() is presentation only — prompts,
Rich rendering, exit codes. All parsing/mutation logic lives in the domain
modules (aiorch.alerts, aiorch.pending, aiorch.context, ...) so agents can
change business rules without touching the CLI surface and vice versa.
Full module map: docs/AI_ARCHITECTURE.md.

Output contract: success lines start with [OK], warnings with [WARN], errors
with [ERROR] — agents parse these prefixes, and the test suite asserts them.
"""
import datetime
import os
import shutil
import subprocess
import sys
import time

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from aiorch.alerts import insert_alert, next_alert_id, parse_alerts
from aiorch.analysis_ui import run_analyze, run_qa
from aiorch.config import load_config
from aiorch.context import (bundle_context, classify_staged_paths,
                            generate_snapshot, inject_snapshot, update_context,
                            update_section)
from aiorch.gitops import (POST_COMMIT_HOOK, PRE_COMMIT_HOOK, GitCommandError,
                           find_secret_files, get_recent_changed_files,
                           get_staged_files, has_merge_conflicts, read_blob,
                           scan_conflict_files, write_git_hook)
from aiorch.handoff_ui import run_handoff_wizard
from aiorch.lint import check_staged_lint, parse_lint_rules
from aiorch.logs import mark_session_recorded, write_ai_gitignore
from aiorch.observability import get_logger
from aiorch.portability import (AGENTS_MD_BLOCK, ANTIGRAVITY_RULE,
                                CLAUDE_MD_BLOCK, render_brief,
                                write_managed_block)
from aiorch.pipeline import (load_envelope, next_step, role_versions,
                             validate_envelope)
from aiorch.pending import (ensure_pending_file, insert_action,
                            next_action_id, parse_pending, resolve_action)
from aiorch.render import (_print_model_recommendations, _run_configured_tests,
                           render_roles_table, render_runs_table)

app = typer.Typer(help="Global AI Orchestrator CLI")
console = Console()


@app.command()
def init():
    """Initialize .ai/ orchestrator folder in current directory."""
    if os.path.exists(".ai"):
        console.print("[yellow]Warning: .ai directory already exists.[/yellow]")
        raise typer.Exit()

    os.makedirs(".ai", exist_ok=True)
    template_dir = os.path.join(os.path.dirname(__file__), "templates")

    if not os.path.exists(template_dir):
        console.print(f"[red]Error: Templates directory {template_dir} not found.[/red]")
        raise typer.Exit(1)

    _runtime_only = {"ANALYSIS.md"}  # auto-generated by `ai-orch analyze`, not init
    for filename in os.listdir(template_dir):
        if filename in _runtime_only:
            continue
        shutil.copy(os.path.join(template_dir, filename), os.path.join(".ai", filename))

    write_ai_gitignore()
    console.print("[green]Successfully initialized .ai/ orchestrator folder![/green]")


@app.command()
def triage():
    """Triage active project alerts and check codebase health."""
    if not os.path.exists(".ai"):
        console.print("[red]Error: .ai/ orchestrator folder not found. Run 'ai-orch init' first.[/red]")
        raise typer.Exit(1)

    alerts = parse_alerts(os.path.join(".ai", "ALERTS.md"))
    console.print(Panel("[bold blue]AI Orchestrator — Project Triage[/bold blue]", expand=False))

    if alerts:
        table = Table(title="Active Alerts", show_header=True, header_style="bold magenta")
        table.add_column("ID", style="dim", width=12)
        table.add_column("Severity", style="bold")
        table.add_column("Title")
        table.add_column("Status", justify="right")
        for alert in alerts:
            sev_color = "red" if alert["severity"] == "P0" else ("yellow" if alert["severity"] == "P1" else "blue")
            table.add_row(alert["id"], f"[{sev_color}]{alert['severity']}[/{sev_color}]",
                          alert["title"], "[green]Open[/green]")
        console.print(table)
    else:
        console.print("[green][OK] No active alerts found in ALERTS.md[/green]")

    pending = parse_pending(os.path.join(".ai", "PENDING.md"))
    if pending:
        pt = Table(title="Pending Manual Actions", header_style="bold cyan")
        pt.add_column("ID", style="dim", width=12)
        pt.add_column("Type")
        pt.add_column("Title")
        for a in pending:
            pt.add_row(a["id"], a["type"], a["title"])
        console.print(pt)

    config_path = os.path.join(".ai", "config.json")
    config = load_config(config_path)
    if os.path.exists(config_path) and not config:
        console.print("[yellow][WARN] .ai/config.json is missing or corrupt — using defaults.[/yellow]")
    _print_model_recommendations(config)

    console.print("\n[bold]Checking for git merge conflicts...[/bold]")
    if os.path.exists(".git"):
        # Fast path: git grep is O(diff); the walk fallback is O(repo-bytes).
        if has_merge_conflicts():
            console.print("[red][ERROR] Merge conflicts detected in working tree.[/red]")
        else:
            console.print("[green][OK] No active merge conflicts detected.[/green]")
    else:
        conflict_files = scan_conflict_files(".")
        for fp in conflict_files:
            console.print(f"[red][ERROR] Merge conflict found in {fp}[/red]")
        if not conflict_files:
            console.print("[green][OK] No active merge conflicts detected.[/green]")

    console.print("\n[bold]Checking for exposed secrets...[/bold]")
    secrets = find_secret_files()
    if secrets:
        for sec in secrets:
            console.print(f"[yellow][WARN] Warning: Potential secret file detected: {sec}[/yellow]")
    else:
        console.print("[green][OK] No secret/credential leaks detected.[/green]")

    test_cmd = config.get("test_command") if config else None
    if test_cmd:
        _run_configured_tests(test_cmd)


@app.command()
def check():
    """Verify that .ai context is updated when other changes are staged."""
    if not os.path.exists(".git"):
        console.print("[yellow]Not a git repository. Skipping context check.[/yellow]")
        raise typer.Exit(0)

    try:
        staged_files = get_staged_files()
    except GitCommandError as e:
        # Exit 0 on git failure: a broken git must never block the commit
        # flow harder than git itself would.
        console.print(f"[yellow]Git check failed: {e}. Skipping.[/yellow]")
        raise typer.Exit(0)

    if not staged_files:
        raise typer.Exit(0)

    codebase_changed, ai_changed = classify_staged_paths(staged_files, read_blob)

    if codebase_changed and not ai_changed:
        console.print(Panel(
            "[red]Error: Staged files detected but .ai/ documentation context was not updated.[/red]\n\n"
            "Please run [bold]ai-orch handoff[/bold] or manually update [bold].ai/CONTEXT.md[/bold] "
            "to describe your changes before committing.",
            title="AI Orchestrator Guard",
            expand=False
        ))
        raise typer.Exit(1)

    rules = parse_lint_rules(os.path.join(".ai", "WHEELS.md"))
    if rules:
        violations = check_staged_lint(staged_files, rules)
        if violations:
            console.print(Panel("[red]WHEELS.md Lint Violations — commit blocked[/red]", expand=False))
            for v in violations:
                console.print(f"[red][X][/red] [bold]{v['file']}:{v['line']}[/bold] — {v['message']}")
                console.print(f"  [dim]{v['code']}[/dim]")
            raise typer.Exit(1)

    console.print("[green][OK] AI orchestrator context update verified.[/green]")
    raise typer.Exit(0)


@app.command("hook-install")
def hook_install():
    """Install git pre-commit and post-commit hooks for context automation."""
    if not os.path.exists(".git"):
        console.print("[red]Error: Not a git repository. Run 'git init' first.[/red]")
        raise typer.Exit(1)

    hook_dir = os.path.join(".git", "hooks")
    os.makedirs(hook_dir, exist_ok=True)
    for name, content in (("pre-commit", PRE_COMMIT_HOOK), ("post-commit", POST_COMMIT_HOOK)):
        path, chmod_warning = write_git_hook(hook_dir, name, content)
        if chmod_warning:
            console.print(f"[yellow]Warning: Could not set executable permission on hook. Reason: {chmod_warning}[/yellow]")
        console.print(f"[green][OK] Git {name} hook installed at {path}[/green]")


@app.command()
def handoff(
    with_snapshot: bool = typer.Option(False, "--snapshot", help="Append codebase symbol snapshot to CONTEXT.md"),
):
    """Run interactive handoff wizard to update .ai documentation and commit changes."""
    run_handoff_wizard(with_snapshot)


@app.command()
def snapshot(
    src: str = typer.Option("src", "--src", help="Source directory to scan (default: src/)"),
    quiet: bool = typer.Option(False, "--quiet", "-q", help="Suppress output (used by post-commit hook)"),
):
    """Scan codebase and inject a symbol snapshot into .ai/CONTEXT.md."""
    if not os.path.exists(".ai"):
        if not quiet:
            console.print("[red]Error: .ai/ not found. Run 'ai-orch init' first.[/red]")
        raise typer.Exit(1)
    snap = generate_snapshot(src)
    inject_snapshot(os.path.join(".ai", "CONTEXT.md"), snap)
    if not quiet:
        console.print("[green][OK] Codebase snapshot injected into CONTEXT.md[/green]")


@app.command()
def update(
    section: str = typer.Option(..., "--section", "-s", help="Section heading to update"),
    value: str = typer.Option(..., "--value", "-v", help="New content for the section (use \\n for newlines)"),
    file: str = typer.Option("CONTEXT.md", "--file", "-f", help=".ai/ file to update"),
):
    """Non-interactively update a section in a .ai/ file (for agent use)."""
    if not os.path.exists(".ai"):
        console.print("[red]Error: .ai/ not found. Run 'ai-orch init' first.[/red]")
        raise typer.Exit(1)
    filepath = os.path.join(".ai", file)
    if update_section(filepath, section, value):
        mark_session_recorded()
        console.print(f"[green][OK] Updated '{section}' in {file}[/green]")
    else:
        console.print(f"[red]Error: Section '{section}' not found in {filepath}[/red]")
        raise typer.Exit(1)


@app.command("action-add")
def action_add(
    title: str = typer.Argument(..., help="Short description of the action"),
    action_type: str = typer.Option("other", "--type", "-t", help="Type: db | infra | other"),
    target: str = typer.Option("[TBD]", "--target", help="Where to perform the action"),
    sql: str = typer.Option("", "--sql", help="SQL to run (for db actions)"),
    steps: str = typer.Option("", "--steps", help="Manual steps description"),
):
    """Add a pending manual action to .ai/PENDING.md."""
    if not title.strip():
        console.print("[red]Error: title cannot be empty.[/red]")
        raise typer.Exit(1)
    if not os.path.exists(".ai"):
        console.print("[red]Error: .ai/ not found (PENDING.md needs it). Run 'ai-orch init' first.[/red]")
        raise typer.Exit(1)
    pending_path = os.path.join(".ai", "PENDING.md")
    ensure_pending_file(pending_path)
    prefix = {"db": "DB", "infra": "INFRA"}.get(action_type.lower(), "ACTION")
    action_id = next_action_id(pending_path, prefix)
    today = datetime.date.today().strftime("%Y-%m-%d")
    data = {"id": action_id, "title": title, "type": action_type, "target": target,
            "sql": sql or None, "steps": steps or None}
    if insert_action(pending_path, data, today):
        console.print(f"[green][OK] Added {action_id}: {title}[/green]")
    else:
        console.print(f"[red]Error: Section for type '{action_type}' not found[/red]")
        raise typer.Exit(1)


@app.command("action-resolve")
def action_resolve(action_id: str = typer.Argument(..., help="Action ID to mark as done (e.g. DB-001)")):
    """Mark a pending action as done and move it to DONE."""
    if not action_id.strip():
        console.print("[red]Error: action_id cannot be empty.[/red]")
        raise typer.Exit(1)
    pending_path = os.path.join(".ai", "PENDING.md")
    if not os.path.exists(pending_path):
        console.print("[red]Error: .ai/PENDING.md not found.[/red]")
        raise typer.Exit(1)
    if resolve_action(pending_path, action_id):
        console.print(f"[green][OK] {action_id} marked as Done[/green]")
    else:
        console.print(f"[red]Error: {action_id} not found in PENDING.md[/red]")
        raise typer.Exit(1)


@app.command()
def analyze():
    """Run specialized analysis of the project and write results to .ai/ANALYSIS.md."""
    run_analyze(get_logger)


@app.command()
def qa():
    """QA review of .ai/ANALYSIS.md — AI first pass, human escalation if ambiguous."""
    run_qa(get_logger)


@app.command()
def export(
    out: str = typer.Option("", "--out", "-o", help="Output file path (default: print to stdout)"),
):
    """Export all .ai/ context files into a single consolidated markdown."""
    if not os.path.exists(".ai"):
        console.print("[red]Error: .ai/ not found. Run 'ai-orch init' first.[/red]")
        raise typer.Exit(1)

    bundle = bundle_context(".ai")

    if out:
        try:
            with open(out, "w", encoding="utf-8") as f:
                f.write(bundle)
            console.print(f"[green][OK] Exported .ai/ context to {out}[/green]")
        except OSError as e:
            console.print(f"[red]Error: Could not write to {out}: {e}[/red]")
            raise typer.Exit(1)
    else:
        # Raw UTF-8 bytes to stdout: Rich would wrap long lines and mangle the
        # Markdown when the output is piped into another model's context.
        sys.stdout.buffer.write(bundle.encode("utf-8"))
        sys.stdout.buffer.write(b"\n")


@app.command()
def observe(
    limit: int = typer.Option(20, "--limit", "-n", help="Number of recent runs to show (default: 20)"),
):
    """Show recent agent run metrics from the Supabase observability store."""
    obs = get_logger()
    if not obs.enabled:
        if getattr(obs, "disabled_reason", None) == "package_missing":
            console.print("[yellow][WARN] Supabase support is not installed.[/yellow]")
            console.print('Install it with: pip install "ai-orchestrator[observability]"')
        else:
            console.print("[yellow][WARN] Supabase not configured.[/yellow]")
            console.print("Set SUPABASE_URL and SUPABASE_ANON_KEY environment variables.")
            console.print("See .env.example for setup instructions.")
            console.print("Run scripts/supabase_schema.sql in your Supabase SQL editor first.")
        raise typer.Exit(0)
    runs = obs.get_recent_runs(limit=limit)
    if not runs:
        console.print("[dim]No agent runs recorded yet.[/dim]")
        raise typer.Exit(0)
    console.print(render_runs_table(runs))


@app.command()
def sync(
    note: str = typer.Option("", "--note", "-n", help="What you did and where you stopped"),
    src: str = typer.Option("src", "--src", help="Source dir for the symbol snapshot"),
):
    """Record the session in .ai/CONTEXT.md from git. Never prompts (for agents)."""
    if not os.path.exists(".ai"):
        console.print("[red]Error: .ai/ not found. Run 'ai-orch init' first.[/red]")
        raise typer.Exit(1)
    try:
        changed = get_recent_changed_files()
    except GitCommandError as e:
        console.print(f"[yellow][WARN] Could not read git state: {e}. Recording the note only.[/yellow]")
        changed = []
    today = datetime.date.today().strftime("%Y-%m-%d")
    context_path = os.path.join(".ai", "CONTEXT.md")
    if not update_context(context_path, today, note, ", ".join(changed)):
        console.print("[red]Error: .ai/CONTEXT.md not found.[/red]")
        raise typer.Exit(1)
    mark_session_recorded()
    console.print(f"[green][OK] Recorded {len(changed)} changed file(s) in CONTEXT.md[/green]")
    if not note:
        console.print("[yellow][WARN] No --note given: git says WHAT changed, only you know WHY.[/yellow]")
    if os.path.isdir(src):
        inject_snapshot(context_path, generate_snapshot(src))
        console.print("[green][OK] Codebase snapshot refreshed[/green]")


@app.command()
def brief(
    out: str = typer.Option("", "--out", "-o", help="Write here instead of stdout (e.g. STATUS.md)"),
):
    """Render .ai/ as one human-readable status page for IDE readers."""
    if not os.path.exists(".ai"):
        console.print("[red]Error: .ai/ not found. Run 'ai-orch init' first.[/red]")
        raise typer.Exit(1)
    config = load_config(os.path.join(".ai", "config.json"))
    today = datetime.date.today().strftime("%Y-%m-%d")
    text = render_brief(".ai", config, today)
    if not out:
        sys.stdout.buffer.write(text.encode("utf-8"))
        sys.stdout.buffer.write(b"\n")
        return
    try:
        with open(out, "w", encoding="utf-8") as f:
            f.write(text)
    except OSError as e:
        console.print(f"[red]Error: Could not write to {out}: {e}[/red]")
        raise typer.Exit(1)
    console.print(f"[green][OK] Wrote human-readable status to {out}[/green]")


@app.command("ide-install")
def ide_install(
    antigravity: bool = typer.Option(True, "--antigravity/--no-antigravity",
                                     help="Also write .agents/rules/ for Antigravity"),
):
    """Teach other IDEs the protocol via AGENTS.md and .agents/ rules."""
    if not os.path.exists(".ai"):
        console.print("[red]Error: .ai/ not found. Run 'ai-orch init' first.[/red]")
        raise typer.Exit(1)
    result = write_managed_block("AGENTS.md", AGENTS_MD_BLOCK, title="Agent instructions")
    console.print(f"[green][OK] AGENTS.md {result}[/green] [dim](read by Antigravity, Cursor, Copilot)[/dim]")
    result = write_managed_block("CLAUDE.md", CLAUDE_MD_BLOCK, title="CLAUDE.md")
    console.print(f"[green][OK] CLAUDE.md {result}[/green] [dim](@imports the arrival protocol every session)[/dim]")
    if antigravity:
        rule = os.path.join(".agents", "rules", "ai-orch.md")
        os.makedirs(os.path.dirname(rule), exist_ok=True)
        with open(rule, "w", encoding="utf-8") as f:
            f.write(ANTIGRAVITY_RULE)
        console.print(f"[green][OK] Wrote {rule}[/green] [dim](trigger: always_on)[/dim]")
    console.print("[dim]Only the managed block is rewritten — your own text is kept.[/dim]")


@app.command()
def validate(
    envelope: str = typer.Argument(..., help="Path to a JSON envelope, or the JSON itself"),
    expect_role: str = typer.Option("", "--role", help="Fail unless the envelope is from this role"),
):
    """Validate a structured inter-agent envelope before passing it on."""
    data, errors = load_envelope(envelope)
    if not errors:
        errors = validate_envelope(data)
        if expect_role and isinstance(data, dict) and data.get("role") != expect_role:
            errors.append({"field": "role",
                           "message": f"expected role {expect_role!r}, got {data.get('role')!r}"})
    if errors:
        console.print(f"[red][ERROR] Envelope rejected — {len(errors)} violation(s)[/red]")
        for e in errors:
            where = f"[bold]{e['field']}[/bold]: " if e["field"] else ""
            console.print(f"  [red]x[/red] {where}{e['message']}")
        raise typer.Exit(1)
    console.print(f"[green][OK] Valid {data['role']} envelope for {data['task_id']}[/green]")
    console.print(f"[green][OK][/green] Next: [cyan]{next_step(data)}[/cyan]")


@app.command()
def roles():
    """Show the configured agent roles and their prompt versions."""
    if not os.path.exists(".ai"):
        console.print("[red]Error: .ai/ not found. Run 'ai-orch init' first.[/red]")
        raise typer.Exit(1)
    versions = role_versions(load_config(os.path.join(".ai", "config.json")))
    if not versions:
        console.print("[yellow][WARN] No agent roles configured in .ai/config.json[/yellow]")
        raise typer.Exit(0)
    console.print(render_roles_table(versions))
    if any(v == "unversioned" for _, v in versions):
        console.print("[yellow][WARN] Unversioned role prompts cannot be changed safely — "
                      "add a \"version\" to each agent in .ai/config.json.[/yellow]")


@app.command()
def setup(
    hooks: bool = typer.Option(True, "--hooks/--no-hooks", help="Install the git guard"),
    ide: bool = typer.Option(True, "--ide/--no-ide", help="Write AGENTS.md / CLAUDE.md / .agents rules"),
):
    """Set a project up in one command: init + hook-install + ide-install."""
    if not os.path.exists(".ai"):
        init()
    else:
        console.print("[yellow][WARN] .ai/ already exists — keeping it.[/yellow]")
    if hooks:
        if os.path.exists(".git"):
            hook_install()
        else:
            console.print("[yellow][WARN] Not a git repository — skipping the commit guard. "
                          "Run 'git init' then 'ai-orch hook-install'.[/yellow]")
    if ide:
        ide_install()
    console.print("\n[green][OK] Ready.[/green] Edit [bold].ai/config.json[/bold] "
                  "(project_name, stack, test_command), then work as usual:")
    console.print("  [dim]arrive →[/dim] ai-orch triage")
    console.print("  [dim]leave  →[/dim] ai-orch sync --note \"where you stopped\"")


if __name__ == "__main__":
    app()
